In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
csvpath_city = os.path.join('raw_data','city_data.csv')
pyber_city_df = pd.read_csv(csvpath_city)
csvpath_ride = os.path.join('raw_data','ride_data.csv')
pyber_ride_df = pd.read_csv(csvpath_ride)

In [4]:
pyber_city_df.head()

             city  driver_count   type
0      Kelseyland            63  Urban
1      Nguyenbury             8  Urban
2    East Douglas            12  Urban
3   West Dawnfurt            34  Urban
4  Rodriguezburgh            52  Urban

In [5]:
pyber_city_df['type'].value_counts()

Urban       66
Suburban    42
Rural       18
Name: type, dtype: int64

In [6]:
pyber_gcity = pyber_ride_df.groupby('city')
pyber_gcity.head()

                      city                 date   fare        ride_id
0                 Sarabury  2016-01-16 13:49:27  38.35  5403689035038
1                South Roy  2016-01-02 18:42:34  17.49  4036272335942
2              Wiseborough  2016-01-21 17:35:29  44.18  3645042422587
3              Spencertown  2016-07-31 14:53:22   6.87  2242596575892
4               Nguyenbury  2016-07-09 04:42:44   6.28  1543057793673
5              New Jeffrey  2016-02-22 18:36:25  36.01  9757888452346
6            Port Johnstad  2016-06-07 02:39:58  17.15  4352278259335
7                Jacobfort  2016-09-20 20:58:37  22.98  1500221409082
8              Travisville  2016-01-15 17:32:02  27.39   850152768361
9               Sandymouth  2016-11-16 07:27:00  21.61  2389035050524
10         New Andreamouth  2016-04-11 07:20:48   7.72  9992929847990
11           New Christine  2016-09-13 15:06:42  24.89  7918411468537
12             Stewartview  2016-03-29 05:15:56  23.88  6778235889588
13          Rodriguezburgh  2016-09-05 05:20:39   4.54  9650770953139
14        West Sydneyhaven  2016-08-02 21:18:44  12.87  7994760397230
15             Swansonbury  2016-07-11 18:42:11  39.30   744481862626
16                Lisatown  2016-07-05 18:09:14   5.82  6370359473201
17               East Erin  2016-11-03 01:03:05   7.51  4744239092530
18         Port Martinberg  2016-01-06 17:11:30   8.66  7298562820881
19             Wiseborough  2016-09-12 18:43:41  26.83  9304728540000
20             Edwardsbury  2016-02-27 03:55:54  20.17  8514523868075
21               Jacobfort  2016-06-12 17:01:29  34.47  4135673527977
22             Pamelahaven  2016-03-26 12:56:57  36.43  3015329826849
23              Fosterside  2016-08-12 11:52:41  28.08   133077693483
24               Jacobfort  2016-09-17 12:38:58  38.25  2182376146051
25        West Sydneyhaven  2016-08-23 14:49:59  36.12  5885997568611
26             West Alexis  2016-01-16 00:33:02  26.62  1574788996743
27             Carrollfort  2016-06-24 20:11:11   6.45  1092683495142
28               New David  2016-01-12 20:48:43  38.68  5229089333754
29             Stewartview  2016-10-15 05:26:40  11.74  8402784599831
...                    ...                  ...    ...            ...
2308        West Kevintown  2016-06-25 08:04:12  24.53  8188407925972
2310        Hernandezshire  2016-04-11 04:44:50  10.41  9823290002445
2312         East Troybury  2016-02-29 07:26:19  14.01  6867080292206
2313          Kennethburgh  2016-02-29 21:50:59  47.48    12105457917
2314           Shelbyhaven  2016-04-21 19:22:03  37.19  5142074323359
2315         North Whitney  2016-02-21 18:20:14  42.01  3306522110065
2319           Jacksonfort  2016-06-09 23:01:40  24.63   978305304720
2322           Stevensport  2016-10-30 16:24:21  22.81  3116198466324
2323         East Troybury  2016-07-01 12:48:05  12.88  5989452220219
2324           Matthewside  2016-02-23 17:46:29  59.65   241191157535
2327        West Kevintown  2016-07-24 13:41:23  11.78  2001192693573
2328              Erikport  2016-01-18 07:11:45  10.66  9287766069118
2331              Erikport  2016-11-28 05:51:38  23.38  6392257942917
2333          Kennethburgh  2016-03-22 18:04:29  25.67  1480709392474
2334          Kennethburgh  2016-03-22 12:38:48  36.54  7210244842844
2336           Stevensport  2016-05-11 12:08:25  41.83  1591306474620
2338          New Johnbury  2016-05-03 04:52:29  40.71  2918447130656
2340           Stevensport  2016-10-13 03:36:59  52.99  9771737428375
2342           Shelbyhaven  2016-06-12 16:57:25  30.18  2015025942653
2344           Shelbyhaven  2016-07-22 05:59:01  10.64  1406024986969
2346           Matthewside  2016-02-23 00:43:51  40.84  8665248512368
2351           Stevensport  2016-02-22 02:45:07  19.91   808097865942
2352  South Elizabethmouth  2016-11-23 07:47:18  46.39  1939838068038
2354           Jacksonfort  2016-10-01 13:41:00  34.17  7750597960630
2356             Horneland  2016-03-25 02:05:42  20.04  5729327140644
2362           Matthewside  2016-05-18 02:00:30  48.67  2049161404256
2363           Matthewside  2016-08-08 14:02:35  24.97  2872494724827
2365  South Elizabethmouth  2016-07-19 09:35:59  31.09  2959749591417
2367          New Johnbury  2016-08-29 02:36:06  18.83  7368222134792
2374  South Elizabethmouth  2016-04-21 10:20:09  16.50  5702608059064

[618 rows x 4 columns]

In [7]:
city_fare = pyber_gcity['fare'].sum()
city_count = pyber_gcity['city'].count()

avg_city = pyber_gcity['fare'].sum()/pyber_gcity['city'].count()

In [8]:
city_count

city
Alvarezhaven            31
Alyssaberg              26
Anitamouth               9
Antoniomouth            22
Aprilchester            19
Arnoldview              31
Campbellport            15
Carrollbury             10
Carrollfort             29
Clarkstad               12
Conwaymouth             11
Davidtown               21
Davistown               25
East Cherylfurt         13
East Douglas            22
East Erin               28
East Jenniferchester    19
East Leslie             11
East Stephen            10
East Troybury            7
Edwardsbury             27
Erikport                 8
Eriktown                19
Floresberg              10
Fosterside              24
Hernandezshire           9
Horneland                4
Jacksonfort              6
Jacobfort               31
Jasonfort               12
                        ..
South Roy               22
South Shannonborough    15
Spencertown             26
Stevensport              5
Stewartview             30
Swansonbury             34
Thomastown              24
Tiffanyton              13
Torresshire             26
Travisville             23
Vickimouth              15
Webstertown             16
West Alexis             20
West Brandy             30
West Brittanyton        24
West Dawnfurt           29
West Evan               12
West Jefferyfurt        21
West Kevintown           7
West Oscar              29
West Pamelaborough      14
West Paulport           17
West Peter              31
West Sydneyhaven        18
West Tony               19
Williamchester          11
Williamshire            31
Wiseborough             19
Yolandafurt             20
Zimmermanmouth          24
Name: city, Length: 125, dtype: int64

In [9]:
avg_city

city
Alvarezhaven            23.928710
Alyssaberg              20.609615
Anitamouth              37.315556
Antoniomouth            23.625000
Aprilchester            21.981579
Arnoldview              25.106452
Campbellport            33.711333
Carrollbury             36.606000
Carrollfort             25.395517
Clarkstad               31.051667
Conwaymouth             34.591818
Davidtown               22.978095
Davistown               21.497200
East Cherylfurt         31.416154
East Douglas            26.169091
East Erin               24.478214
East Jenniferchester    32.599474
East Leslie             33.660909
East Stephen            39.053000
East Troybury           33.244286
Edwardsbury             26.876667
Erikport                30.043750
Eriktown                25.478947
Floresberg              32.310000
Fosterside              23.034583
Hernandezshire          32.002222
Horneland               21.482500
Jacksonfort             32.006667
Jacobfort               24.779355
Jasonfort               27.831667
                          ...
South Roy               26.031364
South Shannonborough    26.516667
Spencertown             23.681154
Stevensport             31.948000
Stewartview             21.614000
Swansonbury             27.464706
Thomastown              30.308333
Tiffanyton              28.510000
Torresshire             24.207308
Travisville             27.220870
Vickimouth              21.474667
Webstertown             29.721250
West Alexis             19.523000
West Brandy             24.157667
West Brittanyton        25.436250
West Dawnfurt           22.330345
West Evan               27.013333
West Jefferyfurt        21.072857
West Kevintown          21.528571
West Oscar              24.280000
West Pamelaborough      33.799286
West Paulport           33.278235
West Peter              24.875484
West Sydneyhaven        22.368333
West Tony               29.609474
Williamchester          34.278182
Williamshire            26.990323
Wiseborough             22.676842
Yolandafurt             27.205500
Zimmermanmouth          28.301667
Length: 125, dtype: float64

In [10]:
urban_city = merge_pyber[merge_pyber['type']=='Urban']['city'].value_counts()
urban_city

NameError: name 'merge_pyber' is not defined

In [11]:
urban_sum = merge_pyber[merge_pyber['type']=='Urban']['fare'].sum()
avg_urban = pyber_gcity['fare'].sum() / urban_city
avg_urban = avg_urban.dropna()
avg_urban

NameError: name 'merge_pyber' is not defined

In [12]:
urban_dcount = pyber_city_df[pyber_city_df['type']=='Urban']
urban_dcount

                 city  driver_count   type
0          Kelseyland            63  Urban
1          Nguyenbury             8  Urban
2        East Douglas            12  Urban
3       West Dawnfurt            34  Urban
4      Rodriguezburgh            52  Urban
5   South Josephville             4  Urban
6    West Sydneyhaven            70  Urban
7         Travisville            37  Urban
8         Torresshire            70  Urban
9           Lisaville            66  Urban
10          Mooreview            34  Urban
11         Smithhaven            67  Urban
12        Carrollfort            55  Urban
13    Port Josephfurt            28  Urban
14   Lake Jeffreyland            15  Urban
15        South Louis            12  Urban
16         West Peter            61  Urban
17    Kimberlychester            13  Urban
18         Alyssaberg            67  Urban
19           Sarabury            46  Urban
20        Yolandafurt             7  Urban
21        Edwardsbury            11  Urban
22    New Andreamouth            42  Urban
23          New David            31  Urban
24         Arnoldview            41  Urban
25       Williamshire            70  Urban
26           Lisatown            47  Urban
27          New Aaron            60  Urban
28        Swansonbury            64  Urban
29         Fosterside            69  Urban
..                ...           ...    ...
36        Spencertown            68  Urban
37        Russellport             9  Urban
38           Maryside            20  Urban
39        West Alexis            47  Urban
40      Port Samantha            55  Urban
41           Eriktown            15  Urban
42        Pamelahaven            30  Urban
43       Aprilchester            49  Urban
44          South Roy            35  Urban
45        Pearsonberg            43  Urban
46         Sandymouth            11  Urban
47          East Erin            43  Urban
48      Port Johnstad            22  Urban
49         Vickimouth            13  Urban
50          Jacobfort            52  Urban
51    South Bryanstad            73  Urban
52         West Oscar            11  Urban
53       Antoniomouth            21  Urban
54        Stewartview            49  Urban
55        West Brandy            12  Urban
56          Davidtown            73  Urban
57        Kellershire            51  Urban
58     Zimmermanmouth            45  Urban
59    Port Martinberg            44  Urban
60     Lake Sarashire             8  Urban
61          Prattfurt            43  Urban
62          Davistown            25  Urban
63   West Jefferyfurt            65  Urban
64      Lake Jennaton            65  Urban
65       Alvarezhaven            21  Urban

[66 rows x 3 columns]

In [13]:
rural_city = merge_pyber[merge_pyber['type']=='Rural']['city'].value_counts()
rural_sum = merge_pyber[merge_pyber['type']=='Rural']['fare'].sum()
avg_rural = pyber_gcity['fare'].sum() / rural_city
avg_rural = avg_rural.dropna()
rural_dcount = pyber_city_df[pyber_city_df['type']=='Rural']
rural_dcount

NameError: name 'merge_pyber' is not defined

In [14]:
merge_pyber[merge_pyber['type']=='Suburban']
sub_test = pyber_city_df[pyber_city_df['type']=='Suburban'].groupby('city')
sub_test.sum()

NameError: name 'merge_pyber' is not defined

In [15]:
sub_city = merge_pyber[merge_pyber['type']=='Suburban']['city'].value_counts()
sub_sum = merge_pyber[merge_pyber['type']=='Suburban']['fare'].sum()
avg_sub = pyber_gcity['fare'].sum() / sub_city
avg_sub = avg_sub.dropna()
sub_dcount = pyber_city_df[pyber_city_df['type']=='Suburban'].groupby('city')
sub_dcount['driver_count'].sum()

NameError: name 'merge_pyber' is not defined

In [16]:
urban_dcount['driver_count']*30,cmap="Red"
sub_dcount['driver_count'].sum()*30,cmap="Blues",
rural_dcount['driver_count']*30,cmap="YlGn",

SyntaxError: can't assign to operator (<ipython-input-16-a11d85f2bf35>, line 1)

In [17]:
fig, ax = plt.subplots()
ax.scatter(urban_city, avg_urban, urban_dcount['driver_count']*10, c ='red', alpha=0.5,edgecolors="grey",linewidth=2)
ax.scatter(sub_city, avg_sub, sub_dcount['driver_count'].sum()*10, c = 'blue', alpha=0.5,edgecolors="grey",linewidth=2)
ax.scatter(rural_city, avg_rural, rural_dcount['driver_count']*10, c = 'yellow', alpha=0.5,edgecolors="grey",linewidth=2)
ax.text(1.3,.5, "Circle size corresponds to driver count", horizontalalignment='center', verticalalignment = 'center', transform=ax.transAxes)
plt.xlim(-1,40)
plt.xlabel('Number of Rides')
plt.ylabel('Average Cost of Ride')
plt.title('Cost of Pyber Rides per city type')
plt.legend(('Urban','Suburban','Rural'),fancybox = True, markerscale = .5, scatterpoints = 1, loc='best')

NameError: name 'urban_city' is not defined

In [ ]:
plt.show()

In [ ]:
pie_data = merge_pyber['type'].value_counts()
pie_data_1 = []
pie_data_1 = [(pie_data[i]) for i in range(0,len(pie_data))]
#for i in range(3):
 #   pie_data_1.append(pie_data[i])
#pie_data = merge_pyber[['type','fare']]
#pie_data['type'].value_counts()
pie_data_1

In [ ]:
labels = ['Urban','Suburban','Rural']
colors = ['Lightcoral','LightBlue','Yellow']
explode = (0.1,0,0)
plt.pie(pie_data_1,explode=explode,labels=labels,colors=colors,autopct="%1.1f%%",shadow=True, startangle=140)
plt.axis('equal')
plt.title("% of Total Rides by City Type")

In [ ]:
plt.show()

In [ ]:
merge_pyber = pd.merge(pyber_ride_df,pyber_city_df, on='city')
test = merge_pyber.groupby('type')
test_2 = test['fare'].sum()
fare_list = [(test_2[i]) for i in range(0,len(test_2))]
fare_list

In [ ]:
labels = ['Rural','Suburban','Urban']
colors = ['Yellow','LightBlue','Lightcoral']
explode = (0,0,0.1)
plt.pie(fare_list,explode=explode,labels=labels,colors=colors,autopct="%1.1f%%",shadow=True, startangle=140)
plt.axis('equal')
plt.title("% of Total Fares by City Type")

In [ ]:
plt.show()

In [ ]:
test['driver_count'].sum()

In [ ]:
pyber_dcount = test['driver_count'].sum()
dcount_list = [pyber_dcount[i] for i in range(0,len(pyber_dcount))]
dcount_list

In [ ]:
labels = ['Rural','Suburban','Urban']
colors = ['Yellow','LightBlue','Lightcoral']
explode = (0,0,0.1)
plt.pie(dcount_list,explode=explode,labels=labels,colors=colors,autopct="%1.1f%%",shadow=True, startangle=140)
plt.axis('equal')
plt.title("% of Total Drivers by City Type")

In [ ]:
plt.show()